name: 'Conventional Commits Changelog Generator'
description: "Automatically generates a structured changelog from conventional commits in your pull request, including breaking changes and upgrade instructions."
author: 'tanmay-pathak'
branding:
  icon: git-pull-request
  color: green
inputs:
  pull_request_url:
    description: 'The GitHub API URL for the pull request to generate the release notes from. This can be obtained from the GitHub actions environment.'
    required: true
  api_token:
    description: 'A GitHub API token. This can be obtained from the GitHub actions environment.'
    required: true
  header:
    description: 'The header (including MarkDown styling) to put the release notes under.'
    required: false
    default: '### Changelog'
  list_item_symbol:
    description: 'The MarkDown list item symbol to use for listing commit messages in the release notes.'
    required: false
    default: '-'
outputs:
  pull_request_description:
    description: 'The generated pull request description.'

runs:
   using: 'docker'
   image: 'docker://tanmaypathak/generate-pull-request-description:latest'
   args:
     - ${{ inputs.pull_request_url }}
     - ${{ inputs.api_token }}
     - ${{ inputs.header }}
     - ${{ inputs.list_item_symbol }}
